import { PropertyCardData } from "@/types/property";

export const mockProperties: PropertyCardData[] = [
	{
		id: "prop_001",
		title: "Spacious 3 Bedroom Flat in Ewet Housing",
		propertyType: "FLAT",
		bedrooms: 3,
		bathrooms: 2,
		area: "Ewet Housing",
		city: "Uyo",
		rent: 450000,
		rentPeriod: "YEAR",
		currency: "NGN",
		negotiable: false,
		amenities: ["Water Supply", "Electricity (NEPA/PHCN)", "Generator", "Parking Space", "Security/Gate", "Fence/Wall"],
		photos: [
			{ url: "/images/placeholder-property-1.jpg", isMain: true },
			{ url: "/images/placeholder-property-2.jpg", isMain: false },
		],
		verificationStatus: "VERIFIED",
		availabilityStatus: "AVAILABLE_NOW",
		isFavourited: false,
		createdAt: new Date("2025-02-10"),
	},
	{
		id: "prop_002",
		title: "Modern 2 Bedroom Flat at Independence Layout",
		propertyType: "FLAT",
		bedrooms: 2,
		bathrooms: 2,
		area: "Independence Layout",
		city: "Uyo",
		rent: 350000,
		rentPeriod: "YEAR",
		currency: "NGN",
		negotiable: true,
		amenities: ["Water Supply", "Prepaid Meter", "Tiled Floor", "POP Ceiling", "Parking Space"],
		photos: [
			{ url: "/images/placeholder-property-2.jpg", isMain: true },
		],
		verificationStatus: "VERIFIED",
		availabilityStatus: "AVAILABLE_NOW",
		isFavourited: true,
		createdAt: new Date("2025-02-08"),
	},
	{
		id: "prop_003",
		title: "Executive 4 Bedroom Duplex in Shelter Afrique",
		propertyType: "DUPLEX",
		bedrooms: 4,
		bathrooms: 3,
		area: "Shelter Afrique",
		city: "Uyo",
		rent: 1200000,
		rentPeriod: "YEAR",
		currency: "NGN",
		negotiable: false,
		amenities: ["Water Supply", "Generator", "Borehole", "Security/Gate", "Fence/Wall", "Boys Quarter (BQ)", "Air Conditioning", "Parking Space"],
		photos: [
			{ url: "/images/placeholder-property-3.jpg", isMain: true },
		],
		verificationStatus: "VERIFIED",
		availabilityStatus: "AVAILABLE_NOW",
		isFavourited: false,
		createdAt: new Date("2025-02-05"),
	},
	{
		id: "prop_004",
		title: "Affordable Self Contain at Aka Road",
		propertyType: "SELF_CONTAIN",
		bedrooms: 1,
		bathrooms: 1,
		area: "Aka Road",
		city: "Uyo",
		rent: 120000,
		rentPeriod: "YEAR",
		currency: "NGN",
		negotiable: true,
		amenities: ["Water Supply", "Tiled Floor", "Prepaid Meter"],
		photos: [
			{ url: "/images/placeholder-property-4.jpg", isMain: true },
		],
		verificationStatus: "PENDING",
		availabilityStatus: "AVAILABLE_NOW",
		isFavourited: false,
		createdAt: new Date("2025-02-12"),
	},
	{
		id: "prop_005",
		title: "Newly Built 3 Bedroom Bungalow at Udo Udoma Avenue",
		propertyType: "BUNGALOW",
		bedrooms: 3,
		bathrooms: 3,
		area: "Udo Udoma Avenue",
		city: "Uyo",
		rent: 650000,
		rentPeriod: "YEAR",
		currency: "NGN",
		negotiable: false,
		amenities: ["Water Supply", "Borehole", "Generator", "Fence/Wall", "Security/Gate", "Wardrobe", "Kitchen Cabinet", "Ensuite"],
		photos: [
			{ url: "/images/placeholder-property-5.jpg", isMain: true },
		],
		verificationStatus: "VERIFIED",
		availabilityStatus: "AVAILABLE_NOW",
		isFavourited: false,
		createdAt: new Date("2025-02-01"),
	},
	{
		id: "prop_006",
		title: "2 Bedroom Flat near Ibom Plaza - Nwaniba Road",
		propertyType: "FLAT",
		bedrooms: 2,
		bathrooms: 1,
		area: "Nwaniba Road",
		city: "Uyo",
		rent: 250000,
		rentPeriod: "YEAR",
		currency: "NGN",
		negotiable: true,
		amenities: ["Water Supply", "Electricity (NEPA/PHCN)", "Tiled Floor", "Fence/Wall"],
		photos: [
			{ url: "/images/placeholder-property-6.jpg", isMain: true },
		],
		verificationStatus: "VERIFIED",
		availabilityStatus: "AVAILABLE_FROM",
		isFavourited: false,
		createdAt: new Date("2025-02-14"),
	},
	{
		id: "prop_007",
		title: "Luxury 5 Bedroom House with BQ in Ewet Housing",
		propertyType: "HOUSE",
		bedrooms: 5,
		bathrooms: 4,
		area: "Ewet Housing",
		city: "Uyo",
		rent: 2500000,
		rentPeriod: "YEAR",
		currency: "NGN",
		negotiable: false,
		amenities: ["Water Supply", "Borehole", "Generator", "Solar Panel", "CCTV", "Swimming Pool", "Boys Quarter (BQ)", "Air Conditioning", "Security/Gate", "Parking Space"],
		photos: [
			{ url: "/images/placeholder-property-7.jpg", isMain: true },
		],
		verificationStatus: "VERIFIED",
		availabilityStatus: "AVAILABLE_NOW",
		isFavourited: true,
		createdAt: new Date("2025-01-28"),
	},
	{
		id: "prop_008",
		title: "Cozy 1 Bedroom Flat at Ikpa Road",
		propertyType: "FLAT",
		bedrooms: 1,
		bathrooms: 1,
		area: "Ikpa Road",
		city: "Uyo",
		rent: 180000,
		rentPeriod: "YEAR",
		currency: "NGN",
		negotiable: true,
		amenities: ["Water Supply", "Tiled Floor", "POP Ceiling", "Prepaid Meter"],
		photos: [
			{ url: "/images/placeholder-property-8.jpg", isMain: true },
		],
		verificationStatus: "PENDING",
		availabilityStatus: "AVAILABLE_NOW",
		isFavourited: false,
		createdAt: new Date("2025-02-13"),
	},
];
