import { PropertyCardData } from "@/types/property";
import { PropertyDetailData } from "@/types/property";

// ── Detailed property data for the single-view page ──

export const mockPropertyDetails: Record<string, PropertyDetailData> = {
	prop_001: {
		id: "prop_001",
		title: "Spacious 3 Bedroom Flat in Ewet Housing",
		propertyType: "FLAT",
		bedrooms: 3,
		bathrooms: 2,
		area: "Ewet Housing",
		city: "Uyo",
		streetAddress: "12 Ewet Housing Estate, Uyo, Akwa Ibom",
		rent: 450000,
		rentPeriod: "YEAR",
		currency: "NGN",
		negotiable: false,
		description:
			"A sharp & spacious self contained apartment. Good light, serene environment, wardrobe kitchen cabinet & other modern facilities available for rent.",
		amenities: [
			"Water Supply",
			"Electricity",
			"Generator",
			"Parking Space",
			"Security/Gate",
			"Fence/Wall",
		],
		photos: [
			{ url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80", isMain: true },
			{ url: "https://images.unsplash.com/photo-1484154218962-a197022b5858?w=600&q=75", isMain: false },
			{ url: "https://images.unsplash.com/photo-1556020685-ae41abfc9365?w=600&q=75", isMain: false },
			{ url: "https://images.unsplash.com/photo-1567016432779-094069958ea5?w=600&q=75", isMain: false },
			{ url: "https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?w=600&q=75", isMain: false },
			{ url: "https://images.unsplash.com/photo-1600121848594-d8644e57abab?w=600&q=75", isMain: false },
			{ url: "https://images.unsplash.com/photo-1598928506311-c55ded91a20c?w=600&q=75", isMain: false },
		],
		verificationStatus: "VERIFIED",
		availabilityStatus: "AVAILABLE_NOW",
		isFavourited: false,
		createdAt: new Date("2025-02-10"),
		listingStatus: "For Rent",
		daysOnUno: 36,
		views: 1570,
		favourites: 53,
		fees: {
			annualRent: 450000,
			legalFeePercent: 10,
			agentFeePercent: 10,
			totalPackage: "590k",
			additional: [
				{ label: "Security Fee", amount: 50000, period: "annually" },
				{ label: "Cleaning Fee", amount: 10000, period: "annually" },
				{ label: "Service Fee", amount: 50000, period: "annually" },
			],
			additionalNote: "Additional fees are compulsory before you move in.",
		},
		additionalInfo: [
			{ label: "Age of house", value: "Virgin House" },
			{ label: "No. of Tenants", value: "5 tenants total" },
			{ label: "Building Type", value: "2 Storey building" },
			{ label: "Year Built", value: "2025" },
			{ label: "Gated Compound", value: "Yes" },
			{ label: "Road Network", value: "Local" },
		],
		features: [
			"Fully Fitted Kitchen",
			"Parking Space",
			"Swimming Pool",
			"Gym",
			"Backup Generator",
		],
		listedBy: { name: "Ryan Cherney", company: "Circle One Realty" },
		listingUpdated: "Dec 23, 2025 at 02:04pm",
		unoChecked: "a few seconds ago",
	},
};

// Extra interior/exterior photos to fill out each property's carousel
const EXTRA_PHOTOS = [
	"https://images.unsplash.com/photo-1484154218962-a197022b5858?w=600&q=75",
	"https://images.unsplash.com/photo-1556020685-ae41abfc9365?w=600&q=75",
	"https://images.unsplash.com/photo-1567016432779-094069958ea5?w=600&q=75",
	"https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?w=600&q=75",
	"https://images.unsplash.com/photo-1600121848594-d8644e57abab?w=600&q=75",
	"https://images.unsplash.com/photo-1598928506311-c55ded91a20c?w=600&q=75",
	"https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=600&q=75",
	"https://images.unsplash.com/photo-1554995207-c18c203602cb?w=600&q=75",
];

/** Pick n extra photos starting at offset i */
function extra(i: number, n = 2) {
	return Array.from({ length: n }, (_, k) => ({
		url: EXTRA_PHOTOS[(i + k) % EXTRA_PHOTOS.length],
		isMain: false,
	}));
}

export const mockProperties: PropertyCardData[] = [
	{
		id: "prop_001",
		title: "Spacious 3 Bedroom Flat in Ewet Housing",
		propertyType: "FLAT",
		bedrooms: 3,
		bathrooms: 2,
		area: "Ewet Housing",
		city: "Uyo",
		rent: 450000,
		rentPeriod: "YEAR",
		currency: "NGN",
		negotiable: false,
		amenities: ["Water Supply", "Electricity", "Generator", "Parking Space", "Security/Gate", "Fence/Wall"],
		photos: [
			{ url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=600&q=75", isMain: true },
			...extra(0),
		],
		verificationStatus: "VERIFIED",
		availabilityStatus: "AVAILABLE_NOW",
		isFavourited: false,
		createdAt: new Date("2025-02-10"),
	},
	{
		id: "prop_002",
		title: "Modern 2 Bedroom Flat at Independence Layout",
		propertyType: "FLAT",
		bedrooms: 2,
		bathrooms: 2,
		area: "Independence Layout",
		city: "Uyo",
		rent: 350000,
		rentPeriod: "YEAR",
		currency: "NGN",
		negotiable: true,
		amenities: ["Water Supply", "Prepaid Meter", "Tiled Floor", "POP Ceiling", "Parking Space"],
		photos: [
			{ url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=600&q=75", isMain: true },
			...extra(1),
		],
		verificationStatus: "VERIFIED",
		availabilityStatus: "AVAILABLE_NOW",
		isFavourited: true,
		createdAt: new Date("2025-02-08"),
	},
	{
		id: "prop_003",
		title: "Executive 4 Bedroom Duplex in Shelter Afrique",
		propertyType: "DUPLEX",
		bedrooms: 4,
		bathrooms: 3,
		area: "Shelter Afrique",
		city: "Uyo",
		rent: 1200000,
		rentPeriod: "YEAR",
		currency: "NGN",
		negotiable: false,
		amenities: ["Water Supply", "Generator", "Borehole", "Security/Gate", "Fence/Wall"],
		photos: [
			{ url: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=600&q=75", isMain: true },
			...extra(2),
		],
		verificationStatus: "VERIFIED",
		availabilityStatus: "AVAILABLE_NOW",
		isFavourited: false,
		createdAt: new Date("2025-02-05"),
	},
	{
		id: "prop_004",
		title: "Affordable Self Contain at Aka Road",
		propertyType: "SELF_CONTAIN",
		bedrooms: 1,
		bathrooms: 1,
		area: "Aka Road",
		city: "Uyo",
		rent: 120000,
		rentPeriod: "YEAR",
		currency: "NGN",
		negotiable: true,
		amenities: ["Water Supply", "Tiled Floor", "Prepaid Meter"],
		photos: [
			{ url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=600&q=75", isMain: true },
			...extra(3),
		],
		verificationStatus: "PENDING",
		availabilityStatus: "AVAILABLE_NOW",
		isFavourited: false,
		createdAt: new Date("2025-02-12"),
	},
	{
		id: "prop_005",
		title: "Newly Built 3 Bedroom Bungalow at Udo Udoma Avenue",
		propertyType: "BUNGALOW",
		bedrooms: 3,
		bathrooms: 3,
		area: "Udo Udoma Avenue",
		city: "Uyo",
		rent: 650000,
		rentPeriod: "YEAR",
		currency: "NGN",
		negotiable: false,
		amenities: ["Water Supply", "Borehole", "Generator", "Fence/Wall", "Security/Gate"],
		photos: [
			{ url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=600&q=75", isMain: true },
			...extra(4),
		],
		verificationStatus: "VERIFIED",
		availabilityStatus: "AVAILABLE_NOW",
		isFavourited: false,
		createdAt: new Date("2025-02-01"),
	},
	{
		id: "prop_006",
		title: "2 Bedroom Flat near Ibom Plaza",
		propertyType: "FLAT",
		bedrooms: 2,
		bathrooms: 1,
		area: "Nwaniba Road",
		city: "Uyo",
		rent: 250000,
		rentPeriod: "YEAR",
		currency: "NGN",
		negotiable: true,
		amenities: ["Water Supply", "Electricity", "Tiled Floor", "Fence/Wall"],
		photos: [
			{ url: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=600&q=75", isMain: true },
			...extra(5),
		],
		verificationStatus: "VERIFIED",
		availabilityStatus: "AVAILABLE_FROM",
		isFavourited: false,
		createdAt: new Date("2025-02-14"),
	},
	{
		id: "prop_007",
		title: "Luxury 5 Bedroom House with BQ in Ewet Housing",
		propertyType: "HOUSE",
		bedrooms: 5,
		bathrooms: 4,
		area: "Ewet Housing",
		city: "Uyo",
		rent: 2500000,
		rentPeriod: "YEAR",
		currency: "NGN",
		negotiable: false,
		amenities: ["Borehole", "Generator", "Solar Panel", "CCTV", "Swimming Pool"],
		photos: [
			{ url: "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=600&q=75", isMain: true },
			...extra(6),
		],
		verificationStatus: "VERIFIED",
		availabilityStatus: "AVAILABLE_NOW",
		isFavourited: true,
		createdAt: new Date("2025-01-28"),
	},
	{
		id: "prop_008",
		title: "Cozy 1 Bedroom Flat at Ikpa Road",
		propertyType: "FLAT",
		bedrooms: 1,
		bathrooms: 1,
		area: "Ikpa Road",
		city: "Uyo",
		rent: 180000,
		rentPeriod: "YEAR",
		currency: "NGN",
		negotiable: true,
		amenities: ["Water Supply", "Tiled Floor", "POP Ceiling", "Prepaid Meter"],
		photos: [
			{ url: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=600&q=75", isMain: true },
			...extra(0, 3),
		],
		verificationStatus: "PENDING",
		availabilityStatus: "AVAILABLE_NOW",
		isFavourited: false,
		createdAt: new Date("2025-02-13"),
	},
	{
		id: "prop_009",
		title: "3 Bedroom Flat at Oron Road",
		propertyType: "FLAT",
		bedrooms: 3,
		bathrooms: 2,
		area: "Oron Road",
		city: "Uyo",
		rent: 400000,
		rentPeriod: "YEAR",
		currency: "NGN",
		negotiable: false,
		amenities: ["Water Supply", "Generator", "Parking Space"],
		photos: [
			{ url: "https://images.unsplash.com/photo-1600573472592-401b489a3cdc?w=600&q=75", isMain: true },
			...extra(1, 3),
		],
		verificationStatus: "VERIFIED",
		availabilityStatus: "AVAILABLE_NOW",
		isFavourited: false,
		createdAt: new Date("2025-02-15"),
	},
	{
		id: "prop_010",
		title: "Self Contain at Use-Offot",
		propertyType: "SELF_CONTAIN",
		bedrooms: 1,
		bathrooms: 1,
		area: "Use-Offot",
		city: "Uyo",
		rent: 100000,
		rentPeriod: "YEAR",
		currency: "NGN",
		negotiable: true,
		amenities: ["Water Supply", "Tiled Floor", "Fence/Wall"],
		photos: [
			{ url: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=600&q=75", isMain: true },
			...extra(2, 3),
		],
		verificationStatus: "PENDING",
		availabilityStatus: "AVAILABLE_NOW",
		isFavourited: false,
		createdAt: new Date("2025-02-16"),
	},
	{
		id: "prop_011",
		title: "2 Bedroom Duplex at Ring Road",
		propertyType: "DUPLEX",
		bedrooms: 2,
		bathrooms: 2,
		area: "Ring Road",
		city: "Uyo",
		rent: 550000,
		rentPeriod: "YEAR",
		currency: "NGN",
		negotiable: false,
		amenities: ["Generator", "Borehole", "Parking Space", "Security/Gate"],
		photos: [
			{ url: "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=600&q=75", isMain: true },
			...extra(3, 3),
		],
		verificationStatus: "VERIFIED",
		availabilityStatus: "AVAILABLE_NOW",
		isFavourited: false,
		createdAt: new Date("2025-02-17"),
	},
	{
		id: "prop_012",
		title: "4 Bedroom House at Abak Road",
		propertyType: "HOUSE",
		bedrooms: 4,
		bathrooms: 3,
		area: "Abak Road",
		city: "Uyo",
		rent: 800000,
		rentPeriod: "YEAR",
		currency: "NGN",
		negotiable: true,
		amenities: ["Water Supply", "Generator", "Fence/Wall", "Parking Space"],
		photos: [
			{ url: "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=600&q=75", isMain: true },
			...extra(4, 3),
		],
		verificationStatus: "VERIFIED",
		availabilityStatus: "AVAILABLE_NOW",
		isFavourited: false,
		createdAt: new Date("2025-02-18"),
	},
	{
		id: "prop_013",
		title: "Mini Flat at Itam",
		propertyType: "FLAT",
		bedrooms: 1,
		bathrooms: 1,
		area: "Itam",
		city: "Uyo",
		rent: 150000,
		rentPeriod: "YEAR",
		currency: "NGN",
		negotiable: true,
		amenities: ["Water Supply", "Electricity", "Tiled Floor"],
		photos: [
			{ url: "https://images.unsplash.com/photo-1600607687644-c7171b42498f?w=600&q=75", isMain: true },
			...extra(5, 3),
		],
		verificationStatus: "PENDING",
		availabilityStatus: "AVAILABLE_NOW",
		isFavourited: false,
		createdAt: new Date("2025-02-19"),
	},
	{
		id: "prop_014",
		title: "3 Bedroom Bungalow at Shelter Afrique",
		propertyType: "BUNGALOW",
		bedrooms: 3,
		bathrooms: 2,
		area: "Shelter Afrique",
		city: "Uyo",
		rent: 700000,
		rentPeriod: "YEAR",
		currency: "NGN",
		negotiable: false,
		amenities: ["Borehole", "Generator", "Security/Gate", "Parking Space"],
		photos: [
			{ url: "https://images.unsplash.com/photo-1600585153490-76fb20a32601?w=600&q=75", isMain: true },
			...extra(6, 3),
		],
		verificationStatus: "VERIFIED",
		availabilityStatus: "AVAILABLE_NOW",
		isFavourited: false,
		createdAt: new Date("2025-02-20"),
	},
];

// Generate details for all mock properties using prop_001 as a template
for (const prop of mockProperties) {
	if (!mockPropertyDetails[prop.id]) {
		mockPropertyDetails[prop.id] = {
			...prop,
			streetAddress: `234 ${prop.area}, ${prop.city}, Akwa Ibom`,
			description:
				"A sharp & spacious self contained apartment. Good light, serene environment, wardrobe kitchen cabinet & other modern facilities available for rent.",
			listingStatus: "For Rent",
			daysOnUno: Math.floor(Math.random() * 60) + 5,
			views: Math.floor(Math.random() * 2000) + 200,
			favourites: Math.floor(Math.random() * 80) + 5,
			fees: {
				annualRent: prop.rent,
				legalFeePercent: 10,
				agentFeePercent: 10,
				totalPackage: `${Math.round((prop.rent * 1.2) / 1000)}k`,
				additional: [
					{ label: "Security Fee", amount: 50000, period: "annually" },
					{ label: "Cleaning Fee", amount: 10000, period: "annually" },
					{ label: "Service Fee", amount: 50000, period: "annually" },
				],
				additionalNote: "Additional fees are compulsory before you move in.",
			},
			additionalInfo: [
				{ label: "Age of house", value: "Virgin House" },
				{ label: "No. of Tenants", value: "5 tenants total" },
				{ label: "Building Type", value: "2 Storey building" },
				{ label: "Year Built", value: "2025" },
				{ label: "Gated Compound", value: "Yes" },
				{ label: "Road Network", value: "Local" },
			],
			features: [
				"Fully Fitted Kitchen",
				"Parking Space",
				"Swimming Pool",
				"Gym",
				"Backup Generator",
			],
			listedBy: { name: "Ryan Cherney", company: "Circle One Realty" },
			listingUpdated: "Dec 23, 2025 at 02:04pm",
			unoChecked: "a few seconds ago",
			photos: [
				...prop.photos,
				{ url: "https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?w=600&q=75", isMain: false },
				{ url: "https://images.unsplash.com/photo-1600121848594-d8644e57abab?w=600&q=75", isMain: false },
				{ url: "https://images.unsplash.com/photo-1598928506311-c55ded91a20c?w=600&q=75", isMain: false },
				{ url: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=600&q=75", isMain: false },
				{ url: "https://images.unsplash.com/photo-1554995207-c18c203602cb?w=600&q=75", isMain: false },
			],
		};
	}
}
