-- Price history + timestamped, de-duped view tracking (TODO item 20).
-- Scoped strictly to NEW objects (PriceHistory, PropertyView). Does NOT touch
-- the Property table, so the `geom` generated column is never re-emitted.
--
-- DDL generated by `prisma migrate diff --from-schema-datamodel <dev schema>
-- --to-schema-datamodel prisma/schema.prisma --script`, then made idempotent.
-- Object names are Prisma's own, copied verbatim — do not rename (item 14).
-- Pinned by src/lib/schema-mappings.test.ts.

CREATE TABLE IF NOT EXISTS "PriceHistory" (
    "id" TEXT NOT NULL,
    "propertyId" TEXT NOT NULL,
    "rent" INTEGER NOT NULL,
    "rentPeriod" "RentPeriod" NOT NULL,
    "listingType" "ListingType" NOT NULL,
    "changedById" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "PriceHistory_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "PropertyView" (
    "id" TEXT NOT NULL,
    "propertyId" TEXT NOT NULL,
    "userId" TEXT,
    "viewerKey" TEXT NOT NULL,
    "day" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "PropertyView_pkey" PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "PriceHistory_propertyId_createdAt_idx" ON "PriceHistory"("propertyId", "createdAt");
CREATE INDEX IF NOT EXISTS "PriceHistory_createdAt_idx" ON "PriceHistory"("createdAt");
CREATE INDEX IF NOT EXISTS "PropertyView_propertyId_createdAt_idx" ON "PropertyView"("propertyId", "createdAt");
CREATE UNIQUE INDEX IF NOT EXISTS "PropertyView_propertyId_viewerKey_day_key" ON "PropertyView"("propertyId", "viewerKey", "day");

-- Foreign keys (guarded so re-runs don't error on existing constraints)
DO $$ BEGIN
  ALTER TABLE "PriceHistory"
    ADD CONSTRAINT "PriceHistory_propertyId_fkey"
    FOREIGN KEY ("propertyId") REFERENCES "Property"("id") ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
  ALTER TABLE "PropertyView"
    ADD CONSTRAINT "PropertyView_propertyId_fkey"
    FOREIGN KEY ("propertyId") REFERENCES "Property"("id") ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN null; END $$;

-- Backfill: one baseline price point per existing listing, dated at creation.
-- Idempotent — skips listings that already have any history. No view backfill:
-- the old counter has no timestamps, and inventing them would be fake data.
INSERT INTO "PriceHistory" ("id", "propertyId", "rent", "rentPeriod", "listingType", "createdAt")
SELECT gen_random_uuid()::text, p."id", p."rent", p."rentPeriod", p."listingType", p."createdAt"
FROM "Property" p
WHERE NOT EXISTS (SELECT 1 FROM "PriceHistory" h WHERE h."propertyId" = p."id");
